/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 1135 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 34 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"

#line 1135 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 38 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"


extern "C" {static int slot_QStyleOptionViewItem_ViewItemFeatures___bool__(PyObject *);}
static int slot_QStyleOptionViewItem_ViewItemFeatures___bool__(PyObject *sipSelf)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 370 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator QStyleOptionViewItem::ViewItemFeatures::Int() != 0);
#else
        sipRes = (sipCpp->operator int() != 0);
#endif
#line 60 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ne__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ne__(PyObject *sipSelf,PyObject *sipArg)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State))
        {
            bool sipRes = 0;

#line 361 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator QStyleOptionViewItem::ViewItemFeatures::Int() != a0->operator QStyleOptionViewItem::ViewItemFeatures::Int());
#else
        sipRes = (sipCpp->operator int() != a0->operator int());
#endif
#line 94 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"
            sipReleaseType(const_cast<QStyleOptionViewItem::ViewItemFeatures *>(a0),sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,ne_slot,sipType_QStyleOptionViewItem_ViewItemFeatures,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___eq__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___eq__(PyObject *sipSelf,PyObject *sipArg)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State))
        {
            bool sipRes = 0;

#line 352 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
#if QT_VERSION >= 0x050000
        sipRes = (sipCpp->operator QStyleOptionViewItem::ViewItemFeatures::Int() == a0->operator QStyleOptionViewItem::ViewItemFeatures::Int());
#else
        sipRes = (sipCpp->operator int() == a0->operator int());
#endif
#line 134 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"
            sipReleaseType(const_cast<QStyleOptionViewItem::ViewItemFeatures *>(a0),sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,eq_slot,sipType_QStyleOptionViewItem_ViewItemFeatures,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___invert__(PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___invert__(PyObject *sipSelf)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;


    {
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStyleOptionViewItem::ViewItemFeatures(~(*sipCpp));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___and__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State, &a1))
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStyleOptionViewItem::ViewItemFeatures((*a0 & a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,and_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___xor__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;
        QStyleOptionViewItem::ViewItemFeatures* a1;
        int a1State = 0;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State, sipType_QStyleOptionViewItem_ViewItemFeatures, &a1, &a1State))
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStyleOptionViewItem::ViewItemFeatures((*a0 ^ *a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);
            sipReleaseType(a1,sipType_QStyleOptionViewItem_ViewItemFeatures,a1State);

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State, &a1))
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes = 0;

#line 346 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
        sipRes = new QStyleOptionViewItem::ViewItemFeatures(*a0 ^ a1);
#line 243 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,xor_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___or__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;
        QStyleOptionViewItem::ViewItemFeatures* a1;
        int a1State = 0;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State, sipType_QStyleOptionViewItem_ViewItemFeatures, &a1, &a1State))
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QStyleOptionViewItem::ViewItemFeatures((*a0 | *a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);
            sipReleaseType(a1,sipType_QStyleOptionViewItem_ViewItemFeatures,a1State);

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State, &a1))
        {
            QStyleOptionViewItem::ViewItemFeatures*sipRes = 0;

#line 341 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
        sipRes = new QStyleOptionViewItem::ViewItemFeatures(*a0 | a1);
#line 295 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return sipConvertFromNewType(sipRes,sipType_QStyleOptionViewItem_ViewItemFeatures,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtGui,or_slot,NULL,sipArg0,sipArg1);
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___int__(PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___int__(PyObject *sipSelf)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;


    {
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = *sipCpp;
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ixor__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QStyleOptionViewItem_ViewItemFeatures)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QStyleOptionViewItem::ViewItemFeatures::operator^=(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ior__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QStyleOptionViewItem_ViewItemFeatures)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QStyleOptionViewItem::ViewItemFeatures::operator|=(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(a0,sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___iand__(PyObject *,PyObject *);}
static PyObject *slot_QStyleOptionViewItem_ViewItemFeatures___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QStyleOptionViewItem_ViewItemFeatures)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

    QStyleOptionViewItem::ViewItemFeatures *sipCpp = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QStyleOptionViewItem_ViewItemFeatures));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->QStyleOptionViewItem::ViewItemFeatures::operator&=(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QStyleOptionViewItem_ViewItemFeatures(void *, const sipTypeDef *);}
static void *cast_QStyleOptionViewItem_ViewItemFeatures(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QStyleOptionViewItem_ViewItemFeatures)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QStyleOptionViewItem_ViewItemFeatures(void *, int);}
static void release_QStyleOptionViewItem_ViewItemFeatures(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QStyleOptionViewItem_ViewItemFeatures(void *, SIP_SSIZE_T, const void *);}
static void assign_QStyleOptionViewItem_ViewItemFeatures(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QStyleOptionViewItem::ViewItemFeatures *>(sipSrc);
}


extern "C" {static void *array_QStyleOptionViewItem_ViewItemFeatures(SIP_SSIZE_T);}
static void *array_QStyleOptionViewItem_ViewItemFeatures(SIP_SSIZE_T sipNrElem)
{
    return new QStyleOptionViewItem::ViewItemFeatures[sipNrElem];
}


extern "C" {static void *copy_QStyleOptionViewItem_ViewItemFeatures(const void *, SIP_SSIZE_T);}
static void *copy_QStyleOptionViewItem_ViewItemFeatures(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QStyleOptionViewItem::ViewItemFeatures(reinterpret_cast<const QStyleOptionViewItem::ViewItemFeatures *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QStyleOptionViewItem_ViewItemFeatures(sipSimpleWrapper *);}
static void dealloc_QStyleOptionViewItem_ViewItemFeatures(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QStyleOptionViewItem_ViewItemFeatures(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QStyleOptionViewItem_ViewItemFeatures(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QStyleOptionViewItem_ViewItemFeatures(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QStyleOptionViewItem::ViewItemFeatures *sipCpp = 0;

    {
        const QStyleOptionViewItem::ViewItemFeatures* a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QStyleOptionViewItem_ViewItemFeatures, &a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionViewItem::ViewItemFeatures(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QStyleOptionViewItem::ViewItemFeatures *>(a0),sipType_QStyleOptionViewItem_ViewItemFeatures,a0State);

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionViewItem::ViewItemFeatures(a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QStyleOptionViewItem::ViewItemFeatures();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_QStyleOptionViewItem_ViewItemFeatures(PyObject *, void **, int *, PyObject *);}
static int convertTo_QStyleOptionViewItem_ViewItemFeatures(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QStyleOptionViewItem::ViewItemFeatures **sipCppPtr = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures **>(sipCppPtrV);

#line 379 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a QStyleOptionViewItem::ViewItemFeatures is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QStyleOptionViewItem_ViewItemFeature)) ||
            sipCanConvertToType(sipPy, sipType_QStyleOptionViewItem_ViewItemFeatures, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QStyleOptionViewItem_ViewItemFeature)))
{
    *sipCppPtr = new QStyleOptionViewItem::ViewItemFeatures(int(SIPLong_AsLong(sipPy)));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<QStyleOptionViewItem::ViewItemFeatures *>(sipConvertToType(sipPy, sipType_QStyleOptionViewItem_ViewItemFeatures, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 590 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtGui/sipQtGuiQStyleOptionViewItemViewItemFeatures.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QStyleOptionViewItem_ViewItemFeatures[] = {
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___bool__, bool_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___ne__, ne_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___eq__, eq_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___invert__, invert_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___and__, and_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___xor__, xor_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___or__, or_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___int__, int_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___ixor__, ixor_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___ior__, ior_slot},
    {(void *)slot_QStyleOptionViewItem_ViewItemFeatures___iand__, iand_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_QStyleOptionViewItem_ViewItemFeatures, "\1QStyleOptionViewItem.ViewItemFeatures(QStyleOptionViewItem.ViewItemFeatures)\n"
    "QStyleOptionViewItem.ViewItemFeatures(int)\n"
    "QStyleOptionViewItem.ViewItemFeatures()");


pyqt4ClassTypeDef sipTypeDef_QtGui_QStyleOptionViewItem_ViewItemFeatures = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QStyleOptionViewItem__ViewItemFeatures,
        {0}
    },
    {
        sipNameNr_ViewItemFeatures,
        {591, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QStyleOptionViewItem_ViewItemFeatures,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    slots_QStyleOptionViewItem_ViewItemFeatures,
    init_type_QStyleOptionViewItem_ViewItemFeatures,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QStyleOptionViewItem_ViewItemFeatures,
    assign_QStyleOptionViewItem_ViewItemFeatures,
    array_QStyleOptionViewItem_ViewItemFeatures,
    copy_QStyleOptionViewItem_ViewItemFeatures,
    release_QStyleOptionViewItem_ViewItemFeatures,
    cast_QStyleOptionViewItem_ViewItemFeatures,
    convertTo_QStyleOptionViewItem_ViewItemFeatures,
    0,
    0,
    0,
    0,
    0
},
    0,
    1,
    0
};
