/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 425 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 34 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtCore/sipQtCoreqintptr.cpp"



extern "C" {static void assign_qintptr(void *, SIP_SSIZE_T, const void *);}
static void assign_qintptr(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<qintptr *>(sipDst)[sipDstIdx] = *reinterpret_cast<const qintptr *>(sipSrc);
}


extern "C" {static void *array_qintptr(SIP_SSIZE_T);}
static void *array_qintptr(SIP_SSIZE_T sipNrElem)
{
    return new qintptr[sipNrElem];
}


extern "C" {static void *copy_qintptr(const void *, SIP_SSIZE_T);}
static void *copy_qintptr(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new qintptr(reinterpret_cast<const qintptr *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_qintptr(void *, int);}
static void release_qintptr(void *ptr, int)
{
    Py_BEGIN_ALLOW_THREADS
    delete reinterpret_cast<qintptr *>(ptr);
    Py_END_ALLOW_THREADS
}



extern "C" {static int convertTo_qintptr(PyObject *, void **, int *, PyObject *);}
static int convertTo_qintptr(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *)
{
    qintptr **sipCppPtr = reinterpret_cast<qintptr **>(sipCppPtrV);

#line 429 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
    qintptr ptr = (qintptr)sipConvertToVoidPtr(sipPy);

    if (!sipIsErr)
        return !PyErr_Occurred();

    // Mapped types deal with pointers, so create one on the heap.
    qintptr *heap = new qintptr;
    *heap = ptr;

    *sipCppPtr = heap;

    // Make sure the pointer doesn't leak.
    return SIP_TEMPORARY;
#line 89 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtCore/sipQtCoreqintptr.cpp"
}


extern "C" {static PyObject *convertFrom_qintptr(void *, PyObject *);}
static PyObject *convertFrom_qintptr(void *sipCppV, PyObject *)
{
   qintptr *sipCpp = reinterpret_cast<qintptr *>(sipCppV);

#line 445 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/sip/QtCore/qglobal.sip"
    return sipConvertFromVoidPtr((void *)*sipCpp);
#line 100 "/home/saiaravindbv/repos/graphite/dependencies/PyQt-x11-gpl-4.11.3/QtCore/sipQtCoreqintptr.cpp"
}


sipMappedTypeDef sipTypeDef_QtCore_qintptr = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_qintptr,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_qintptr,
    array_qintptr,
    copy_qintptr,
    release_qintptr,
    convertTo_qintptr,
    convertFrom_qintptr
};
