# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'num2.ui'
#
# Created: Sat Mar 14 17:29:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import dialog

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_numPad(QtGui.QWidget):
    def __init__(self):
        super(Ui_numPad,self).__init__()
        self.setupUi()
        self.show()
    # parameters=[]
    # inputString=""
    def setupUi(self):
        self.setObjectName(_fromUtf8("numPad"))
        self.resize(340, 510)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setAcceptDrops(False)
        self.layoutWidget = QtGui.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 281, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.x = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x.sizePolicy().hasHeightForWidth())
        self.x.setSizePolicy(sizePolicy)
        self.x.setObjectName(_fromUtf8("x"))
        self.horizontalLayout.addWidget(self.x)
        self.y = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y.sizePolicy().hasHeightForWidth())
        self.y.setSizePolicy(sizePolicy)
        self.y.setObjectName(_fromUtf8("y"))
        self.horizontalLayout.addWidget(self.y)
        self.z = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z.sizePolicy().hasHeightForWidth())
        self.z.setSizePolicy(sizePolicy)
        self.z.setObjectName(_fromUtf8("z"))
        self.horizontalLayout.addWidget(self.z)
        # self.a = QtGui.QPushButton(self.layoutWidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.a.sizePolicy().hasHeightForWidth())
        # self.a.setSizePolicy(sizePolicy)
        # self.a.setObjectName(_fromUtf8("a"))
        # self.horizontalLayout.addWidget(self.a)
        # self.b = QtGui.QPushButton(self.layoutWidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.b.sizePolicy().hasHeightForWidth())
        # self.b.setSizePolicy(sizePolicy)
        # self.b.setObjectName(_fromUtf8("b"))
        # self.horizontalLayout.addWidget(self.b)
        # self.c = QtGui.QPushButton(self.layoutWidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.c.sizePolicy().hasHeightForWidth())
        # self.c.setSizePolicy(sizePolicy)
        # self.c.setObjectName(_fromUtf8("c"))
        # self.horizontalLayout.addWidget(self.c)
        self.layoutWidget_2 = QtGui.QWidget(self)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 120, 281, 128))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.n1 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n1.sizePolicy().hasHeightForWidth())
        self.n1.setSizePolicy(sizePolicy)
        self.n1.setObjectName(_fromUtf8("n1"))
        self.gridLayout.addWidget(self.n1, 0, 0, 1, 1)
        self.n2 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n2.sizePolicy().hasHeightForWidth())
        self.n2.setSizePolicy(sizePolicy)
        self.n2.setObjectName(_fromUtf8("n2"))
        self.gridLayout.addWidget(self.n2, 0, 1, 1, 1)
        self.n3 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n3.sizePolicy().hasHeightForWidth())
        self.n3.setSizePolicy(sizePolicy)
        self.n3.setObjectName(_fromUtf8("n3"))
        self.gridLayout.addWidget(self.n3, 0, 2, 1, 1)
        self.n4 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n4.sizePolicy().hasHeightForWidth())
        self.n4.setSizePolicy(sizePolicy)
        self.n4.setObjectName(_fromUtf8("n4"))
        self.gridLayout.addWidget(self.n4, 0, 3, 1, 1)
        self.n5 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n5.sizePolicy().hasHeightForWidth())
        self.n5.setSizePolicy(sizePolicy)
        self.n5.setObjectName(_fromUtf8("n5"))
        self.gridLayout.addWidget(self.n5, 0, 4, 1, 1)
        self.n6 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n6.sizePolicy().hasHeightForWidth())
        self.n6.setSizePolicy(sizePolicy)
        self.n6.setObjectName(_fromUtf8("n6"))
        self.gridLayout.addWidget(self.n6, 0, 5, 1, 1)
        self.n7 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n7.sizePolicy().hasHeightForWidth())
        self.n7.setSizePolicy(sizePolicy)
        self.n7.setObjectName(_fromUtf8("n7"))
        self.gridLayout.addWidget(self.n7, 1, 0, 1, 1)
        self.n8 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n8.sizePolicy().hasHeightForWidth())
        self.n8.setSizePolicy(sizePolicy)
        self.n8.setObjectName(_fromUtf8("n8"))
        self.gridLayout.addWidget(self.n8, 1, 1, 1, 1)
        self.n9 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n9.sizePolicy().hasHeightForWidth())
        self.n9.setSizePolicy(sizePolicy)
        self.n9.setObjectName(_fromUtf8("n9"))
        self.gridLayout.addWidget(self.n9, 1, 2, 1, 1)
        self.n0 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n0.sizePolicy().hasHeightForWidth())
        self.n0.setSizePolicy(sizePolicy)
        self.n0.setObjectName(_fromUtf8("n0"))
        self.gridLayout.addWidget(self.n0, 1, 3, 1, 1)
        self.LeftBracket = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftBracket.sizePolicy().hasHeightForWidth())
        self.LeftBracket.setSizePolicy(sizePolicy)
        self.LeftBracket.setObjectName(_fromUtf8("LeftBracket"))
        self.gridLayout.addWidget(self.LeftBracket, 1, 4, 1, 1)
        self.rightBracket = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightBracket.sizePolicy().hasHeightForWidth())
        self.rightBracket.setSizePolicy(sizePolicy)
        self.rightBracket.setObjectName(_fromUtf8("rightBracket"))
        self.gridLayout.addWidget(self.rightBracket, 1, 5, 1, 1)
        self.lessThan = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lessThan.sizePolicy().hasHeightForWidth())
        self.lessThan.setSizePolicy(sizePolicy)
        self.lessThan.setObjectName(_fromUtf8("lessThan"))
        self.gridLayout.addWidget(self.lessThan, 2, 0, 1, 1)
        self.lessThanEq = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lessThanEq.sizePolicy().hasHeightForWidth())
        self.lessThanEq.setSizePolicy(sizePolicy)
        self.lessThanEq.setObjectName(_fromUtf8("lessThanEq"))
        self.gridLayout.addWidget(self.lessThanEq, 2, 1, 1, 1)
        self.greaterThan = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greaterThan.sizePolicy().hasHeightForWidth())
        self.greaterThan.setSizePolicy(sizePolicy)
        self.greaterThan.setObjectName(_fromUtf8("greaterThan"))
        self.gridLayout.addWidget(self.greaterThan, 2, 2, 1, 1)
        self.greaterThanEq = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greaterThanEq.sizePolicy().hasHeightForWidth())
        self.greaterThanEq.setSizePolicy(sizePolicy)
        self.greaterThanEq.setObjectName(_fromUtf8("greaterThanEq"))
        self.gridLayout.addWidget(self.greaterThanEq, 2, 3, 1, 1)
        self.point = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point.sizePolicy().hasHeightForWidth())
        self.point.setSizePolicy(sizePolicy)
        self.point.setObjectName(_fromUtf8("point"))
        self.gridLayout.addWidget(self.point, 2, 4, 1, 1)
        self.equal = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equal.sizePolicy().hasHeightForWidth())
        self.equal.setSizePolicy(sizePolicy)
        self.equal.setObjectName(_fromUtf8("equal"))
        self.gridLayout.addWidget(self.equal, 2, 5, 1, 1)
        self.add = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setObjectName(_fromUtf8("add"))
        self.gridLayout.addWidget(self.add, 3, 0, 1, 1)
        self.subtract = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtract.sizePolicy().hasHeightForWidth())
        self.subtract.setSizePolicy(sizePolicy)
        self.subtract.setObjectName(_fromUtf8("subtract"))
        self.gridLayout.addWidget(self.subtract, 3, 1, 1, 1)
        self.mult = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mult.sizePolicy().hasHeightForWidth())
        self.mult.setSizePolicy(sizePolicy)
        self.mult.setObjectName(_fromUtf8("mult"))
        self.gridLayout.addWidget(self.mult, 3, 2, 1, 1)
        self.div = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.div.sizePolicy().hasHeightForWidth())
        self.div.setSizePolicy(sizePolicy)
        self.div.setObjectName(_fromUtf8("div"))
        self.gridLayout.addWidget(self.div, 3, 3, 1, 1)
        self.e = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e.sizePolicy().hasHeightForWidth())
        self.e.setSizePolicy(sizePolicy)
        self.e.setObjectName(_fromUtf8("e"))
        self.gridLayout.addWidget(self.e, 3, 4, 1, 1)
        self.clr = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clr.sizePolicy().hasHeightForWidth())
        self.clr.setSizePolicy(sizePolicy)
        self.clr.setObjectName(_fromUtf8("clr"))
        self.gridLayout.addWidget(self.clr, 3, 5, 1, 1)
        self.plot = QtGui.QPushButton(self)
        self.plot.setGeometry(QtCore.QRect(40, 450, 111, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setObjectName(_fromUtf8("plot"))

        self.clear = QtGui.QPushButton(self)
        self.clear.setGeometry(QtCore.QRect(190, 450, 98, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setObjectName(_fromUtf8("clear"))

        self.lineEdit = QtGui.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 281, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.widget = QtGui.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(30, 260, 281, 171))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.trCombo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trCombo.sizePolicy().hasHeightForWidth())
        self.trCombo.setSizePolicy(sizePolicy)
        self.trCombo.setObjectName(_fromUtf8("trCombo"))
        self.trCombo.addItem(_fromUtf8(""))
        self.trCombo.addItem(_fromUtf8(""))
        self.trCombo.addItem(_fromUtf8(""))
        self.trCombo.addItem(_fromUtf8(""))
        self.trCombo.addItem(_fromUtf8(""))
        self.trCombo.addItem(_fromUtf8(""))

        #self.trCombo.setEditable(True)

        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.trCombo)
        self.label_2 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.logCombo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logCombo.sizePolicy().hasHeightForWidth())
        self.logCombo.setSizePolicy(sizePolicy)
        self.logCombo.setObjectName(_fromUtf8("logCombo"))
        self.logCombo.addItem(_fromUtf8(""))
        self.logCombo.addItem(_fromUtf8(""))
        self.logCombo.addItem(_fromUtf8(""))
        self.logCombo.addItem(_fromUtf8(""))

        #self.logCombo.setEditable(True) 

        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.logCombo)
        self.label_3 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.expCombo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expCombo.sizePolicy().hasHeightForWidth())
        self.expCombo.setSizePolicy(sizePolicy)
        self.expCombo.setObjectName(_fromUtf8("expCombo"))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        self.expCombo.addItem(_fromUtf8(""))
        
        #self.expCombo.setEditable(True) 

        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.expCombo)
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.calCombo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calCombo.sizePolicy().hasHeightForWidth())
        self.calCombo.setSizePolicy(sizePolicy)
        self.calCombo.setObjectName(_fromUtf8("calCombo"))
        self.calCombo.addItem(_fromUtf8(""))
        self.calCombo.addItem(_fromUtf8(""))

        #self.calCombo.setEditable(True) 

        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.calCombo)
        self.label_5 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.linCombo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linCombo.sizePolicy().hasHeightForWidth())
        self.linCombo.setSizePolicy(sizePolicy)
        self.linCombo.setObjectName(_fromUtf8("linCombo"))
        self.linCombo.addItem(_fromUtf8(""))
        # self.linCombo.addItem(_fromUtf8(""))
        # self.linCombo.addItem(_fromUtf8(""))
        # self.linCombo.addItem(_fromUtf8(""))

        #self.linCombo.setEditable(True) 

        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.linCombo)

        self.retranslateUi()
        QtCore.QObject.connect(self.trCombo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.comboEvent)
        QtCore.QObject.connect(self.logCombo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.comboEvent)
        QtCore.QObject.connect(self.expCombo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.comboEvent)
        QtCore.QObject.connect(self.calCombo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.comboEvent)
        #QtCore.QObject.connect(self.linCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.comboEvent)
        QtCore.QObject.connect(self.linCombo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), self.comboEvent)
        QtCore.QObject.connect(self.clear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit.clear)
        QtCore.QObject.connect(self.clr, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit.backspace)

        QtCore.QObject.connect(self.x, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.y, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.z, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        # QtCore.QObject.connect(self.a, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        # QtCore.QObject.connect(self.b, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        # QtCore.QObject.connect(self.c, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n9, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.n0, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.LeftBracket, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.rightBracket, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.lessThan, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.lessThanEq, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.greaterThan, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.point, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.equal, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.greaterThanEq, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.add, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.subtract, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.div, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.mult, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        QtCore.QObject.connect(self.e, QtCore.SIGNAL(_fromUtf8("clicked()")), self.buttonEvent)
        #QtCore.QObject.connect(self.plot,QtCore.SIGNAL(_fromUtf8("clicked()")), self.getInput)

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("numPad", "Form", None))
        self.x.setText(_translate("numPad", "x", None))
        self.y.setText(_translate("numPad", "y", None))
        self.z.setText(_translate("numPad", "z", None))
        # self.a.setText(_translate("numPad", "a", None))
        # self.b.setText(_translate("numPad", "b", None))
        # self.c.setText(_translate("numPad", "c", None))
        self.n1.setText(_translate("numPad", "1", None))
        self.n2.setText(_translate("numPad", "2", None))
        self.n3.setText(_translate("numPad", "3", None))
        self.n4.setText(_translate("numPad", "4", None))
        self.n5.setText(_translate("numPad", "5", None))
        self.n6.setText(_translate("numPad", "6", None))
        self.n7.setText(_translate("numPad", "7", None))
        self.n8.setText(_translate("numPad", "8", None))
        self.n9.setText(_translate("numPad", "9", None))
        self.n0.setText(_translate("numPad", "0", None))
        self.LeftBracket.setText(_translate("numPad", "(", None))
        self.rightBracket.setText(_translate("numPad", ")", None))
        self.lessThan.setText(_translate("numPad", "<", None))
        self.lessThanEq.setText(_translate("numPad", "<=", None))
        self.greaterThan.setText(_translate("numPad", ">", None))
        self.greaterThanEq.setText(_translate("numPad", ">=", None))
        self.point.setText(_translate("numPad", ".", None))
        self.equal.setText(_translate("numPad", "=", None))
        self.add.setText(_translate("numPad", "+", None))
        self.subtract.setText(_translate("numPad", "-", None))
        self.mult.setText(_translate("numPad", "*", None))
        self.div.setText(_translate("numPad", "/", None))
        self.e.setText(_translate("numPad", "e", None))
        self.clr.setText(_translate("numPad", "DEL", None))
        self.clr.setShortcut(_translate("numPad", "Backspace", None))
        self.plot.setShortcut(_translate("numPad", "Return", None))
        self.plot.setText(_translate("numPad", "PLOT", None))
        self.clear.setText(_translate("numPad", "CLEAR", None))
        self.label.setText(_translate("numPad", "Trigonometry", None))
        self.trCombo.setItemText(0, _translate("numPad", "sin(x)", None))
        self.trCombo.setItemText(1, _translate("numPad", "cos(x)", None))
        self.trCombo.setItemText(2, _translate("numPad", "tan(x)", None))
        self.trCombo.setItemText(3, _translate("numPad", "cosec(x)", None))
        self.trCombo.setItemText(4, _translate("numPad", "sec(x)", None))
        self.trCombo.setItemText(5, _translate("numPad", "cot(x)", None))
        self.label_2.setText(_translate("numPad", "Logarithmic", None))
        self.logCombo.setItemText(0, _translate("numPad", "log2(x)", None))
        self.logCombo.setItemText(1, _translate("numPad", "ln(x)", None))
        self.logCombo.setItemText(2, _translate("numPad", "log10(x)", None))
        self.logCombo.setItemText(3, _translate("numPad", "logb(x)", None))
        self.label_3.setText(_translate("numPad", "Exponential", None))
        self.expCombo.setItemText(0, _translate("numPad", "e^x", None))
        self.expCombo.setItemText(1, _translate("numPad", "√a", None))
        self.expCombo.setItemText(2, _translate("numPad", "x^y", None))
        self.expCombo.setItemText(3, _translate("numPad", "x^2", None))
        self.expCombo.setItemText(4, _translate("numPad", "x^3", None))
        self.expCombo.setItemText(5, _translate("numPad", "cube root(x)", None))
        self.expCombo.setItemText(6, _translate("numPad", "n root(x)", None))
        self.label_4.setText(_translate("numPad", "Calculus", None))
        self.calCombo.setItemText(0, _translate("numPad", "derivation", None))
        self.calCombo.setItemText(1, _translate("numPad", "integrate", None))
        self.label_5.setText(_translate("numPad", "Linear Algebra", None))
        # self.linCombo.setItemText(0, _translate("numPad", "y=ax+b", None))
        self.linCombo.setItemText(0, _translate("numPad", "a*x+b*y", None))
        # self.linCombo.setItemText(2, _translate("numPad", "ax+by>0", None))
        # self.linCombo.setItemText(3, _translate("numPad", "ax+by>=0", None))


    def comboEvent(self,text):
        # parameters=[]
        if(self.sender()==self.linCombo):
            try:
                dia=dialog.Dialog()
                temp=dia.showDialog("Enter values(a,b)",2).split(",")
                # parameters.append(int(temp[0]))
                # parameters.append(int(temp[1]))
            except:
                return QtGui.QWidget
        elif(text=="logb(x)"):
            try:
                dia=dialog.Dialog()
                temp=dia.showDialog("Enter value of b",1).strip("\n")
                #parameters.append(int(temp))
            except:
                return QtGui.QWidget
        curr = self.lineEdit.text()+text
        self.lineEdit.setText(curr)
        return QtGui.QWidget


    def buttonEvent(self):
        curr = self.lineEdit.text()+self.sender().text()
        self.lineEdit.setText(curr)
        return QtGui.QWidget

    def getInput(self):
        #inputString = self.lineEdit.text()
        return QtGui.QWidget

    # def __call__(self):
    #     return self.lineEdit.text()


'''
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    #numPad = QtGui.QWidget()
    ui = Ui_numPad()
    # ui.setupUi()
    # ui.show()
    sys.exit(app.exec_())
'''
