/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.6
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 78 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtHelp/qhelpcontentwidget.sip"
#include <qhelpcontentwidget.h>
#line 34 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"

#line 107 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qurl.sip"
#include <qurl.h>
#line 38 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 41 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 174 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 44 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 47 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 774 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 50 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 483 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 53 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 261 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 56 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 59 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qregion.sip"
#include <qregion.h>
#line 62 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qrect.sip"
#include <qrect.h>
#line 65 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 1135 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 68 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 338 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 71 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 533 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 74 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 33 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 77 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 94 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 80 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 83 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 86 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 89 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 92 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 36 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 95 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qheaderview.sip"
#include <qheaderview.h>
#line 98 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 94 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 101 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 127 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 104 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 656 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 107 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 274 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 110 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qabstractitemdelegate.sip"
#include <qabstractitemdelegate.h>
#line 113 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 570 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 116 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 514 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 119 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 748 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 122 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 801 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 125 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 790 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 128 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 131 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 34 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qobject.sip"
#include <qobject.h>
#line 134 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 137 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qsize.sip"
#include <qsize.h>
#line 140 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 143 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 120 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 146 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 149 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qscrollbar.sip"
#include <qscrollbar.h>
#line 152 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 627 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 155 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 356 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 158 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 39 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 161 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qframe.sip"
#include <qframe.h>
#line 164 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 167 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 170 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 39 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 173 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 33 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 176 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 179 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 182 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 185 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 37 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 188 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 191 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 194 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qfont.sip"
#include <qfont.h>
#line 197 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 200 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 203 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 616 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 206 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 605 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 209 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 863 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 212 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 412 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 215 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 583 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 218 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 557 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 221 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 33 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 224 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 61 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 227 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 39 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qx11info_x11.sip"
#include <qx11info_x11.h>
#line 230 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 120 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 233 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qaction.sip"
#include <qaction.h>
#line 236 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 239 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 242 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 245 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 248 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 251 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qicon.sip"
#include <qicon.h>
#line 254 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 257 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 260 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 355 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 263 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 33 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 266 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 120 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qlist.sip"
#include <qlist.h>
#line 269 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qthread.sip"
#include <qthread.h>
#line 272 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 35 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 275 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"
#line 31 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 278 "/home/archen/MyRepos/graphite/PyQt-x11-gpl-4.11.3/QtHelp/sipQtHelpQHelpContentWidget.cpp"


PyDoc_STRVAR(doc_QHelpContentWidget_indexOf, "QHelpContentWidget.indexOf(QUrl) -> QModelIndex");

extern "C" {static PyObject *meth_QHelpContentWidget_indexOf(PyObject *, PyObject *);}
static PyObject *meth_QHelpContentWidget_indexOf(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QUrl* a0;
        QHelpContentWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QHelpContentWidget, &sipCpp, sipType_QUrl, &a0))
        {
            QModelIndex*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QModelIndex(sipCpp->indexOf(*a0));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QModelIndex,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpContentWidget, sipName_indexOf, doc_QHelpContentWidget_indexOf);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QHelpContentWidget(void *, const sipTypeDef *);}
static void *cast_QHelpContentWidget(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QHelpContentWidget)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QTreeView)->ctd_cast((QTreeView *)(QHelpContentWidget *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpContentWidget(void *, int);}
static void release_QHelpContentWidget(void *sipCppV,int)
{
    QHelpContentWidget *sipCpp = reinterpret_cast<QHelpContentWidget *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QHelpContentWidget(sipSimpleWrapper *);}
static void dealloc_QHelpContentWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpContentWidget(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpContentWidget[] = {{723, 1, 1}};


static PyMethodDef methods_QHelpContentWidget[] = {
    {SIP_MLNAME_CAST(sipName_indexOf), meth_QHelpContentWidget_indexOf, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpContentWidget_indexOf)}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QHelpContentWidget[] = {
    {"linkActivated(QUrl)", "\1QHelpContentWidget.linkActivated[QUrl]", 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_QtHelp_QHelpContentWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QHelpContentWidget,
        {0}
    },
    {
        sipNameNr_QHelpContentWidget,
        {0, 0, 1},
        1, methods_QHelpContentWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QHelpContentWidget,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpContentWidget,
    0,
    0,
    0,
    release_QHelpContentWidget,
    cast_QHelpContentWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpContentWidget::staticMetaObject,
    0,
    signals_QHelpContentWidget,
};
